name: CI Pipeline

on:
  push:
    branches:
      - dev

permissions:
  contents: write 
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Test Docker Image
        run: |
          chmod +x ./start.sh
          ./start.sh

      - name: Wait for Container to Start
        run: sleep 10

      - name: Test Application Endpoint
        run: |
          curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8080 || exit 1

      - name: Stop and Remove Container
        if: always()
        run: |
          docker stop hello-web-container || true
          docker rm hello-web-container || true

  create-pull-request:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create pull request
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -B main -H dev --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'